{
    "84": [
        {
            "status": "error",
            "error": "unsupported operand type(s) for *: 'float' and 'decimal.Decimal'\nTraceback (most recent call last):\n  File \"c:\\Users\\ahmet\\OneDrive\\Masa\u00fcst\u00fc\\Balina Megasolo\\last\\balina\\backend\\trade_engine\\process\\run_bot.py\", line 74, in run_bot\n    exec(strategy_code, allowed_globals)\n  File \"<string>\", line 15, in <module>\n  File \"C:\\Users\\ahmet\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 10374, in apply\n    return op.apply().__finalize__(self, method=\"apply\")\n           ^^^^^^^^^^\n  File \"C:\\Users\\ahmet\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\apply.py\", line 916, in apply\n    return self.apply_standard()\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ahmet\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\apply.py\", line 1063, in apply_standard\n    results, res_index = self.apply_series_generator()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ahmet\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\apply.py\", line 1081, in apply_series_generator\n    results[i] = self.func(v, *self.args, **self.kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<string>\", line 8, in get_position\nTypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'\n"
        }
    ],
    "83": [
        {
            "status": "error",
            "error": "name 'input' is not defined\nTraceback (most recent call last):\n  File \"c:\\Users\\ahmet\\OneDrive\\Masa\u00fcst\u00fc\\Balina Megasolo\\last\\balina\\backend\\trade_engine\\process\\run_bot.py\", line 72, in run_bot\n    exec(indicator['code'], allowed_globals)\n  File \"<string>\", line 1, in <module>\nNameError: name 'input' is not defined\n"
        }
    ]
}